---
name: Auto merge
on:
  pull_request:
jobs:
  auto-merge:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_merge.yml@1.0.9
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      tfcheck: '_example / Evaluate Terraform versions (1.6.5, ./_example/) / Get min/max versions'
...
